[package]
name = "zksync_os_hashed_fibonacci"
version = "0.1.0"
edition = "2021"
authors = ["ADI Foundation"]
homepage = "https://adi.foundation/"
repository = "https://github.com/ADI-Foundation-Labs/ADI-Stack-Airbender-System/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync", "zk", "risc-v"]
categories = ["cryptography"]

[dependencies]
common_constants = { path = "../../common_constants"}
riscv_common = { path = "../../riscv_common", features = ["boot_sequence", "no_memset_override"] }

[profile.release]
lto = true


[workspace]