[build]
target = "riscv32i-unknown-none-elf"
rustflags = [
  # "--cfg", "no_global_oom_handling",
  "-C", "target-feature=-unaligned-scalar-mem,+relax,+zimop",
  "-C", "link-arg=-Tsrc/lds/memory.x",
  "-C", "link-arg=-Tsrc/lds/link.x",
  "-C", "link-arg=--save-temps",
  "-C", "force-frame-pointers",
  # reproducibility
  "--remap-path-prefix= /=/src",
  "-C", "link-arg=--build-id=sha1",
  "-C", "codegen-units=1",
]

