[package]
name = "zksync_os_opcode_smoke"
version = "0.1.0"
edition = "2021"
authors = ["ADI Foundation"]
homepage = "https://adi.foundation/"
repository = "https://github.com/ADI-Foundation-Labs/ADI-Stack-Airbender-System/"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync", "zk", "risc-v"]
categories = ["cryptography"]

[dependencies]
riscv_common = { path = "../../riscv_common" }

[profile.release]
lto = true

[workspace]
